### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lgc2333** [lgc2333/nonebot-plugin-autoreply#11]
### Important

- [ ] 换用 Alconna，使用其 MessageTemplate

### Others

- [ ] 自定义调用API，借用CQ码，写法： `[CQ:api,api=xxx,param1=yyy,param2=zzz]`
- [ ] regex类变量，例如 `{random|\d|\d}`，`Dict[str, Callable[..., Any]]`
- [ ] 检测到 CQ 码 file 为文件夹时，随机抽取其中文件发送
